version: "3.9"

services:
  app:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    image: bobobox-app:latest
    container_name: bobobox-app
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    restart: always
